service: CGC-python-etl

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  profile: serverless-admin
  region: af-south-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
      Resource: ${ssm:/projects/cgc-etl/dynamodb/table_arn}
  stage: dev

functions:
  main:
    handler: app.main
  alert:
    handler: dynamodb_sns.alert

resources:
  Resources:
    MainArnParameter:
      Type: AWS::SSM::Parameter
      Properties:
        Name: /projects/cgc-etl/lambda/main_arn
        Type: String
        Value: !GetAtt [ MainLambdaFunction, Arn ]
        Description: The ARN of my main Lambda

plugins:
  - serverless-python-requirements

package:
  exclude:
    - node_modules/**
    - terraform/**

custom:
  pythonRequirements:
    dockerizePip: non-linux