service: CGC-python-etl

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  profile: serverless-admin
  region: af-south-1
  stage: dev
  environment:
    SNS_TOPIC_ARN: ${ssm:/projects/cgc-etl/sns/dynamodb_alert_topic_arn}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
      Resource: ${ssm:/projects/cgc-etl/dynamodb/table_arn}
    - Effect: "Allow"
      Action:
      - dynamodb:GetRecords
      - dynamodb:GetShardIterator
      - dynamodb:DescribeStream
      - dynamodb:ListStreams
      Resource: ${ssm:/projects/cgc-etl/dynamodb/stream_arn}
    - Effect: "Allow"
      Action:
      - SNS:Publish
      Resource: ${ssm:/projects/cgc-etl/sns/dynamodb_alert_topic_arn}

functions:
  main:
    handler: app.main
    layers:
      - arn:aws:lambda:${self:provider.region}:392341123054:layer:AWSLambda-Python38-SciPy1x:26
      - {Ref: PandasLambdaLayer}
  alert:
    handler: dynamodb_sns.alert

resources:
  Resources:
    MainArnParameter:
      Type: AWS::SSM::Parameter
      Properties:
        Name: /projects/cgc-etl/lambda/main_arn
        Type: String
        Value: !GetAtt [ MainLambdaFunction, Arn ]
        Description: The ARN of my main Lambda

package:
  exclude:
    - node_modules/**
    - terraform/**
  individually: true

# AWS Lambda Layers
layers:
  Pandas:
    path: layers/pandas
    name: ${self:service}-Python38-Pandas1-1-2
    description: Pandas 1.1.2 with Python 3.8
    compatibleRuntimes:
      - python3.8
